### PR TITLE
Render fixed sample values in JSON Schema

### LINKED ISSUE #343: JSON Schema generation doesn't show fixed sample values
Given the following example structure:

```apib
+ Response 200 (application/json)
    + Attributes
        - example1: my value (fixed)
        - example2 (fixed)
            - Sample
                my value
```

The generated JSON Schema is the following:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "example1": {
      "type": "string",
      "enum": [
        "my value"
      ]
    },
    "example2": {
      "type": "string"
    }
  },
  "required": [
    "example1",
    "example2"
  ]
}
```

It should, instead be the following (note, enum value for example2).

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "example1": {
      "type": "string",
      "enum": [
        "my value"
      ]
    },
    "example2": {
      "type": "string",
      "enum": [
        "my value"
      ]
    }
  },
  "required": [
    "example1",
    "example2"
  ]
}
```

Drafter version 2.3.1.

### PR DESCRIPTION
**Pull request by kylef**
Fixes #343

### CODE REVIEW

File: src/refract/JSONSchemaVisitor.cc [hunk 1]
```diff
@@ -151,14 +151,14 @@ namespace refract
...
     void JSONSchemaVisitor::primitiveType(const T& e)
     {
-        const typename T::ValueType *v = GetValue<T>(e);
+        const typename T::ValueType *value = GetValue<T>(e);
 
-        if (v) {
+        if (value) {
             setPrimitiveType(e);
 
-            if (fixed && !e.empty()) {
```
Comment (kylef) [inline src/refract/JSONSchemaVisitor.cc]: Instead, we've already checked for `value`. The value might be a sample or default value instead of the `e.content`.

File: test/fixtures/render/fixed-attributes-section.ast.json [hunk 2]
```diff
@@ -45,7 +45,7 @@
                           }
                         ],
                         "body": "{\n  \"name\": \"pavan\"\n}",
-                        "schema": "{\n  \"$schema\": \"http://json-schema.org/draft-04/schema#\",\n  \"type\": \"object\",\n  \"properties\": {\n    \"name\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"additionalProperties\": false\n}",
+                        "schema": "{\n  \"$schema\": \"http://json-schema.org/draft-04/schema#\",\n  \"type\": \"object\",\n  \"properties\": {\n    \"name\": {\n      \"type\": \"string\",\n      \"enum\": [\n        \"pavan\"\n      ]\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"additionalProperties\": false\n}",
```
Comment (kylef) [inline test/fixtures/render/fixed-attributes-section.ast.json]: Seems like this was incorrect before?

```
# GET /
+ Response 200 (application/json)
    + Attributes (User, fixed)

# Data Structures
## User
+ name: *pavan*
```

File: test/fixtures/render/fixed-named-type.ast.json [hunk 3]
```diff
@@ -45,7 +45,7 @@
                           }
                         ],
                         "body": "{\n  \"name\": \"pavan\"\n}",
-                        "schema": "{\n  \"$schema\": \"http://json-schema.org/draft-04/schema#\",\n  \"type\": \"object\",\n  \"properties\": {\n    \"name\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"additionalProperties\": false\n}",
+                        "schema": "{\n  \"$schema\": \"http://json-schema.org/draft-04/schema#\",\n  \"type\": \"object\",\n  \"properties\": {\n    \"name\": {\n      \"type\": \"string\",\n      \"enum\": [\n        \"pavan\"\n      ]\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"additionalProperties\": false\n}",
```
Comment (kylef) [inline test/fixtures/render/fixed-named-type.ast.json]:
```apib
# GET /
+ Response 200 (application/json)
    + Attributes (User)

# Data Structures
## User (fixed)
+ name: *pavan*
```

File: test/fixtures/schema/array-fixed-samples-complex.json [hunk 4]
```diff
@@ -182,7 +182,7 @@
...
...               "content": "{\n  \"$schema\": \"http://json-schema.org/draft-04/schema#\",\n  \"type\": \"object\",\n  \"properties\": {\n    \"tags\": {\n      \"type\": \"array\",\n      \"items\": [\n        {\n          \"type\": \"string\",\n          \"enum\": [\n            \"hello\"\n          ]\n        },\n        {\n          \"type\": \"object\",\n          \"properties\": {\n            \"name\": {\n              \"type\": \"string\",\n              \"enum\": [\n                \"snow\"\n              ]\n            },\n            \"color\": {\n              \"type\": \"string\",\n              \"enum\": [\n                \"white\"\n              ]\n            },\n            \"description\": {\n              \"type\": \"string\",\n              \"enum\": [\n                \"\"\n              ]\n            }\n          },\n          \"required\": [\n            \"name\",\n            \"color\",\n            \"description\"\n          ],\n          \"additionalProperties\": false\n        },\n        {\n          \"type\": \"string\",\n          \"enum\": [\n            \"world\"\n          ]\n        }\n      ]\n    }\n  },\n  \"required\": [\n    \"tags\"\n  ]\n}"
```
Comment (kylef) [inline test/fixtures/schema/array-fixed-samples-complex.json]:
```apib
# Resource [/example]

## Action [GET]

+ Response 200 (application/json)

    + Attributes
        - tags (array, fixed)
            - hello (string)
            - *42* (number)
            - (object)
                - name: *snow* (string)
                - color: white
                - description (string)
            - world
```

File: test/fixtures/schema/object-fixed.json [hunk 5]
```diff
@@ -143,7 +143,7 @@
...
+                              "content": "{\n  \"$schema\": \"http://json-schema.org/draft-04/schema#\",\n  \"type\": \"object\",\n  \"properties\": {\n    \"person\": {\n      \"type\": \"object\",\n      \"properties\": {\n        \"first_name\": {\n          \"type\": \"string\",\n          \"enum\": [\n            \"\"\n          ]\n        },\n        \"last_name\": {\n          \"type\": \"string\",\n          \"enum\": [\n            \"\"\n          ]\n        }\n      },\n      \"required\": [\n        \"first_name\",\n        \"last_name\"\n      ],\n      \"additionalProperties\": false\n    }\n  },\n  \"required\": [\n    \"person\"\n  ]\n}"
```
Comment (kylef) [inline test/fixtures/schema/object-fixed.json]: This is the only change that concerns me a little. What should we do for fixed values where the user did not supply any value?

Before we was treating this as non-fixed silently. Now it would use the "default" value, i.e, empty string etc. Should we perhaps issue a warning? Is this acceptable/expected?


```apib
# Resource [/example]

## Action [GET]

+ Response 200 (application/json)

    + Attributes
        - person (object, fixed)
            - first_name
            - last_name
```

File: CHANGELOG.md [hunk 6]
```diff
@@ -36,7 +36,14 @@
 * Correctly parse object samples within arrays.
   [#246](https://github.com/apiaryio/drafter/issues/246)
 
-* Correctly render JSON Schema when `fixed` is used on attributes section or named type [mson#60](https://github.com/apiaryio/mson/issues/60)
+* Correctly render JSON Schema when `fixed` is used on attributes section or
+  named type.
+  [mson#60](https://github.com/apiaryio/mson/issues/60)
+
+* Ensure that sample values are rendered in JSON Schema when using the `fixed`
```
Comment (pksunkara) [inline CHANGELOG.md]: I have merged the 3.0.0, so please change this.

File: test/fixtures/schema/array-fixed-types-only.json [hunk 7]
```diff
@@ -125,7 +125,7 @@
                               "attributes": {
                                 "contentType": "application/schema+json"
                               },
-                              "content": "{\n  \"$schema\": \"http://json-schema.org/draft-04/schema#\",\n  \"type\": \"object\",\n  \"properties\": {\n    \"tags\": {\n      \"type\": \"array\",\n      \"items\": [\n        {\n          \"type\": \"string\"\n        },\n        {\n          \"type\": \"number\"\n        }\n      ]\n    }\n  },\n  \"required\": [\n    \"tags\"\n  ]\n}"
+                              "content": "{\n  \"$schema\": \"http://json-schema.org/draft-04/schema#\",\n  \"type\": \"object\",\n  \"properties\": {\n    \"tags\": {\n      \"type\": \"array\",\n      \"items\": [\n        {\n          \"type\": \"string\",\n          \"enum\": [\n            \"\"\n          ]\n        },\n        {\n          \"type\": \"number\",\n          \"enum\": [\n            0\n          ]\n        }\n      ]\n    }\n  },\n  \"required\": [\n    \"tags\"\n  ]\n}"
```
Comment (pksunkara) [inline test/fixtures/schema/array-fixed-types-only.json]: I think the empty values here inside `enum` is an issue.

File: test/fixtures/schema/object-fixed.json (hunk 5 above)
Comment (pksunkara) [inline test/fixtures/schema/object-fixed.json]: I think empty string is okay. Because fixed also kinda means required and we use empty string for required.

File: test/fixtures/schema/array-fixed-types-only.json (hunk 7 above)
Comment (pksunkara) [inline test/fixtures/schema/array-fixed-types-only.json]: Hmm.. this might be related to https://github.com/apiaryio/drafter/pull/358/files#r69289920. Can you check once? If yes, no need to change this then.

**Comment by pksunkara** [comment]
LGTM. A few comments.

File: test/fixtures/schema/array-fixed-types-only.json (hunk 7 above)
Comment (kylef) [inline test/fixtures/schema/array-fixed-types-only.json]: Here is the APIB for this test:

```
# Resource [/example]

## Action [GET]

+ Response 200 (application/json)

    + Attributes
      - tags (array, fixed)
          - (string)
          - (number)
```

**Comment by kylef** [comment]
I've updated changelog entry from master.

**Comment by goganchic** [comment]
I think this PR brakes down fixed-keyword for arrays.

api blueprint:

```
# GET /ab
- response 200 (application/json)
    - Attributes(object, required)
        - result (array[MyObj], required, fixed)

# Data Structures

## MyObj

- Include Mixin
- field1: foo (string, required, sample)
- field2: bar (string, required, sample)
```

Json Schema before PR:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "result": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "field3": {
              "type": "string"
            },
            "field1": {
              "type": "string"
            },
            "field2": {
              "type": "string"
            }
          },
          "required": [
            "field3",
            "field1",
            "field2"
          ],
          "additionalProperties": false
        }
      ]
    }
  },
  "required": [
    "result"
  ]
}
```

Json Schema after PR:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "result": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "field3": {
              "type": "string",
              "enum": [
                "buz"
              ]
            },
            "field1": {
              "type": "string",
              "enum": [
                "foo"
              ]
            },
            "field2": {
              "type": "string",
              "enum": [
                "bar"
              ]
            }
          },
          "required": [
            "field3",
            "field1",
            "field2"
          ],
          "additionalProperties": false
        }
      ]
    }
  },
  "required": [
    "result"
  ]
}
```

If I do not set fixed for array - drafter generates json schema without array items description.

**Comment by pksunkara** [comment]
The JSON Schema rendered after the PR is correct. JSON Schema before the PR is a bug. `fixed` by default is inherited by everything underneath it unless you specify otherwise. Unfortunately, we do not have a way to define top-level `fixed` only. /cc @kylef

**Comment by goganchic** [comment]
@pksunkara how can I write api blueprint which will generate description of array items? Not only

```
    "result": {
      "type": "array"
    }
```

but

```
    "result": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "field1": {
              "type": "string"
            },
            "field2": {
              "type": "string"
            }
          },
          "required": [
            "field3",
            "field1",
            "field2"
          ],
          "additionalProperties": false
        }
      ]
    }
```

**Comment by pksunkara** [comment]
You have to use `fixed` for it which means the items inside will also inherit fixed, which is why I was talking about a root level `fixed` which doesn't exist as of now.

**Comment by goganchic** [comment]
Is this issue connected with https://github.com/apiaryio/mson/issues/31 ? It looks like a regression for me

**Comment by pksunkara** [comment]
@goganchic No but is a bit related to apiaryio/mson#60. I think I am confusing your use case. Can you describe what the MSON you are writing is along with what JSON Schema you are expecting? Thanks.

**Comment by goganchic** [comment]
I want to write something like

```
# GET /ab
- response 200 (application/json)
    - Attributes(object, required)
        - result (array[MyObj], required)

# Data Structures

## MyObj

- field1: foo (string, required, sample)
- field2: bar (string, required, sample)
```

and get json schema like

```
    "result": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "field1": {
              "type": "string"
            },
            "field2": {
              "type": "string"
            }
          },
          "required": [
            "field1",
            "field2"
          ]
        }
      ]
    }
```

but now I get array without any description of items:

```
    "result": {
      "type": "array"
    }
```

the most important thing for me is generation of description of internal array structure. Before this PR I could use a hack with `fixed` keyword, but now I can not. So is there any opened ticket about this problem? I want to fix it because in my APIs there are a lot of complicated arrays and it is very important to to see a description of internal structure of array in json schema. I looked through https://github.com/apiaryio/mson/issues/31 and it looks similar.

**Comment by pksunkara** [comment]
There is a bit of discussion going on regarding this at apiaryio/mson#66.
