### PR TITLE
Fix inheritance

### LINKED ISSUE #98: MSON - named type based on primitive is wrongly rendered
While we try to define new type of Element eg. **Data** who inherit from **StringElement** it returns wrong body example

e.g
```apib
# GET /sample
+ Response 200 (application/json)
    + Attributes
        + message: (Message)

# Data Structures

# Message
+ created (Date)
+ text (string)

# Date (string)

## Sample
2012-12-01
```

returns:
```
...
"body": "{\n  \"message\": {\n    \"created\": {},\n    \"text\": \"\"\n  }\n}"
...
```

Expected output is:
```
....
"body": "{\n  \"message\": {\n    \"created\":  "2012-12-01",\n    \"text\": \"\"\n  }\n}"

...
```

### LINKED ISSUE #176: Regression - enum inline definition pick into JSON "array" instead of member
```
# Data Structures
## A
+ a: X,Y (B, required)

## B (enum)
- P
- Q

# GET /
+ Response 200 (application/json)
    + Attributes (A)
```

## Current
```json
{"a": ["X", "Y"] }
```

## Expected
```json
{"a": "X"}
```

Releated #136

### PR DESCRIPTION
**Pull request by klokane**
Reworked inheritance:
- fix correct order in `extend` element for inheritance from older ancestor to newest
- allow inheritance for primitive members
- fixed inheritance for `RenderJSONVisitor`
- introduce ` ElementMerger` to handle correctly/standardized  way inheritance resolve
- refactoring `ExpandVisitor`
- move members out of `IElement` (it now provide just Interface and some helpers)
- little refactoring in `TypeQueryVisitor` (expose enum ast typedef)
- correct order "data structures" according to membership/inheritance (most dependent objects are registered latest)

To be resolved: 
- cripled some schema test after rebase (done)
- add test for primitive types inheritance (done)
- add test for complex membership/inheritance 
(test are created, just needs to added to repository and check if schema is generated correctly) 

Resolved issues:
- fix #98
- fix #176

### CODE REVIEW

File: src/RefractAPI.cc [hunk 1]
```diff
@@ -6,7 +6,6 @@
 //  Copyright (c) 2015 Apiary Inc. All rights reserved.
 //
 
-#include <iterator>
```
Comment (kylef) [inline src/RefractAPI.cc]: Curious, any particular reason you've moved this down? In most languages it preferred to put system includes before local includes.

Comment (klokane) [inline src/RefractAPI.cc]: In short? In C/C++ is prefered system down :)

In long:
```
// file a.h
std::string fn();
```

```
// file a.cc
#include <string>
#include "a.h"

std::string fn() { return "hello"; }
```

`a.cc` will be compiled ok

but
```
// file: b.cc
#include "a.h"

something...
```

compilation will fail with something like `unknown type 'std::string'`

Comment (kylef) [inline src/RefractAPI.cc]: Ah that's a good point. It's no longer been a problem in Objective-C with the introduction of clang modules. I completely forgot it's not standard/default across all compilers.

:+1:

**Comment by klokane** [comment]
Last commit (103c0bf) is for discussion, it fix problems with schema fixtures, but fixtures definition in schema are not correct. There should be selected one value for `enum` instead of array of possible values.

**Comment by klokane** [comment]
Hmm interesting, sent patch (commented out part) fixes #176 :)

**Comment by klokane** [comment]
Curent statust
- @w-vi is checking changes in JSON Schema rendering
- working on fix: https://github.com/apiaryio/drafter/blob/klokane/fix-inheritance/test/fixtures/mson/primitive-variables.apib

(member `c8` should be expanded as object)

**Comment by klokane** [comment]
@w-vi rebased on top of your patch, added fix for for **variable property name**
Ready for  code review

**Comment by klokane** [comment]
@w-vi it I'm going thru issues. It seems, this patch fix #47 too, can you please check it and confirm or deny?

**Comment by w-vi** [comment]
@klokane I have check the latest master and the issue is fixed there as well, so I don't know when it was fixed but it is fixed.

**Comment by klokane** [comment]
ok

**Comment by klokane** [comment]
There is something wrong with emscripten build, have no idea what happen
```
FAIL ../test/fixtures/mson/primitive-variables.apib (ast)

/home/ubuntu/drafter/emcc/drafter.nomem.js:1
aughtException",(function(ex){if(!(ex instanceof ExitStatus)){throw ex}}));Mod
                                                                    ^
TypeError: Cannot call method 'split' of undefined
    at Object.lineDiff.tokenize (/home/ubuntu/drafter/node_modules/diff/lib/diff/line.js:20:32)
    at Object.diff (/home/ubuntu/drafter/node_modules/diff/lib/diff/base.js:36:39)
    at Object.diffJson (/home/ubuntu/drafter/node_modules/diff/lib/diff/json.js:33:19)
    at /home/ubuntu/drafter/emcc/test-drafter:125:25
    at /home/ubuntu/drafter/node_modules/async/lib/async.js:721:13
    at /home/ubuntu/drafter/node_modules/async/lib/async.js:52:16
    at /home/ubuntu/drafter/node_modules/async/lib/async.js:269:32
    at /home/ubuntu/drafter/node_modules/async/lib/async.js:44:16
    at /home/ubuntu/drafter/node_modules/async/lib/async.js:718:17
    at /home/ubuntu/drafter/node_modules/async/lib/async.js:167:37
npm ERR! Test failed.  See above for more details.
```

**Comment by w-vi** [comment]
@klokane I am looking into it right now

File: src/refract/Element.cc [hunk 2]
```diff
@@ -129,4 +131,245 @@ namespace refract
...
+                }
+                return true;
+            }
+        };
+    }
+
+    void ExtendElement::set(const ExtendElement::ValueType& val)
+    {
+        if (!TypeChecker(val)) {
+            throw LogicError("ExtendElement require to be composed form Elements of Equal Type");
```
Comment (klokane) [inline src/refract/Element.cc]: use same message like line 191

File: src/refract/Element.cc [hunk 3]
```diff
@@ -129,4 +131,245 @@ namespace refract
...
+                                (*item)->value.second = (*it)->value.second->clone();
+                            }
+                        }
+                    }
+                }
+            };
+
+            /**
+             * precondition - target && append element MUST BE of same type
+             * we use static_cast<> without checking type t is responsibility if caller
```
Comment (klokane) [inline src/refract/Element.cc]: s/if/of/

File: src/RefractAPI.cc [hunk 4]
```diff
@@ -82,10 +84,145 @@ namespace drafter {
...
+            }
+        }
+
+        bool hasMember(const snowcrash::DataStructure* object, const snowcrash::DataStructure* member) {
+            MembersMap::const_iterator members = objectToMembers.find(name(object));
+            if (members == objectToMembers.end()) {
+                return false;
+            }
+
+            return members->second.find(name(member)) == members->second.end();
```
Comment (klokane) [inline src/RefractAPI.cc]: swap condition to `!=` to be conform to name of function

File: src/refract/IsExpandableVisitor.cc [hunk 5]
```diff
@@ -37,6 +37,13 @@ namespace refract
             }
         };
 
+        //template <>
```
Comment (klokane) [inline src/refract/IsExpandableVisitor.cc]: remove commented code

File: src/refract/SerializeVisitor.cc [hunk 6]
```diff
@@ -35,6 +35,18 @@ namespace refract
             return s.get();
         }
 
+        template <typename T>
+        sos::Array SerializeValuelist(const T& e) {
```
Comment (klokane) [inline src/refract/SerializeVisitor.cc]: typo `s/SerializeValuelist/SerializeValueList`

File: src/refract/Element.cc [hunk 7]
```diff
@@ -129,4 +131,243 @@ namespace refract
...
+
+                    case TypeQueryVisitor::Object:
+                        doMerge<ObjectElement>(result, e);
+                        return;
+
+                    case TypeQueryVisitor::Member:
+                        doMerge<MemberElement>(result, e);
+                        return;
+
+                    case TypeQueryVisitor::Null:
```
Comment (w-vi) [inline src/refract/Element.cc]: shouldn't these two do something, at least throw an error or something? Or put comment why we can do nothing

File: src/refract/Element.cc [hunk 8]
```diff
@@ -129,4 +131,243 @@ namespace refract
...
+            };
+
+            template <typename T>
+            struct InfoMerge {
+                IElement::MemberElementCollection& info;
+                InfoMerge(IElement::MemberElementCollection& info) : info(info) {}
+
+                void operator()(const IElement::MemberElementCollection& append) {
+                    for (IElement::MemberElementCollection::const_iterator it = append.begin() ; it != append.end() ; ++it) {
+                        if (StringElement* key = TypeQueryVisitor::as<StringElement>((*it)->value.first)) {
```
Comment (w-vi) [inline src/refract/Element.cc]: Is this correct? It looks like it is only overwriting existing keys but new keys are just skipped.

Comment (klokane) [inline src/refract/Element.cc]: Probably not, will fix

Comment (klokane) [inline src/refract/Element.cc]: It should append new one, and replace old one like for values. Additionally there are some condition for some special key in meta `id`, .`namespace` and `prefix`

File: src/refract/Element.cc (hunk 7 above)
Comment (klokane) [inline src/refract/Element.cc]: ok will add explaining comment

**Comment by w-vi** [comment]
Not really part of this PR but when doing the review I came across this bit https://github.com/apiaryio/drafter/blob/klokane/fix-inheritance/src/refract/IsExpandableVisitor.cc#L24

It looks like this is condition is redundant isn't it?  couldn't we just do `if (type == "ref")` because basically only when type is `ref` we want it to return `true`. Am I correct? 

Also couple of lines down https://github.com/apiaryio/drafter/blob/klokane/fix-inheritance/src/refract/IsExpandableVisitor.cc#L32 it looks like it can be just `return checkElement(e)`

**Comment by klokane** [comment]
good catch, I mean in older version of code was no `ref` part of `isReserved()` that is probably reason. Will remove.

**Comment by w-vi** [comment]
@klokane  rest of the bugs I can't find  :)

**Comment by klokane** [comment]
Yeaah, they are really good hidden!

**Comment by klokane** [comment]
@w-vi i look at condition `!isReserved(type) || type == "ref";` it has different meaning there is `not reserved` (mean inherited type) or `it is reference`. So this condition is correct.

**Comment by klokane** [comment]
@w-vi review addressed. There are no tests :( in current tests implementation it is not possible to prepare test with comparable output.

We need implement querying for refract to build tests for similar cases

**Comment by w-vi** [comment]
My part is done, I think it's ready for merge ... so leaving it to @pksunkara if he has anything to comment on

**Comment by klokane** [comment]
BTW why "continuous-integration/appveyor" CI is (again and again) yellow? I mean, we should remove it form CI proces it it does not work.

**Comment by pksunkara** [comment]
We should be relying on the other 2 green things, not the `continuous-integration/appveyor` which is just an aggregator.

```
 continuous-integration/appveyor/branch
 continuous-integration/appveyor/pr
```

The yellow one is an issue but hopefully appveyor will fix it soon. We can try to forget about it until then since we need the other CI statuses.

**Comment by klokane** [comment]
@pksunkara yes, I know about it. But if I remember it is not working for few months. It is confusing

**Comment by pksunkara** [comment]
> yes, I know about it. But if I remember it is not working for few months. It is confusing

I know and I feel the same. :sob: But we really do need the windows CI. :disappointed:

File: test/fixtures/mson/inheritance-primitive.apib [hunk 9]
```diff
@@ -0,0 +1,27 @@
...
++ text (string)
+
+# Date (string)
+
+## Sample
+2012-12-00
+
+# Date2 (Date1)
+## Sample
+2012-12-01
```
Comment (pksunkara) [inline test/fixtures/mson/inheritance-primitive.apib]: Did you mean to have `2012-12-02` here?

File: src/RefractAPI.cc [hunk 10]
```diff
@@ -82,10 +84,145 @@ namespace drafter {
         }
     }
 
+    struct InheritanceComparator {
```
Comment (pksunkara) [inline src/RefractAPI.cc]: This looks good but I need to look into this again more carefully.

File: src/RefractDataStructure.cc [hunk 11]
```diff
@@ -723,12 +760,22 @@ namespace drafter {
...
 
             snowcrash::SourceMap<mson::Literal> sourceMap;
             sourceMap.sourceMap.append(property.sourceMap.name.sourceMap);
 
+            // check if base variable type is StringElement
+            if (!property.node.name.variable.typeDefinition.empty()) {
+                const std::string& type = property.node.name.variable.typeDefinition.typeSpecification.name.symbol.literal;
+                if (!type.empty()) {
+                    if (!refract::TypeQueryVisitor::as<refract::StringElement>(FindRootAncestor(type, GetNamedTypesRegistry()))) {
+                        throw snowcrash::Error("variable named property must be string ot its sub-type", snowcrash::MSONError);
```
Comment (pksunkara) [inline src/RefractDataStructure.cc]: `ot` -> `or`

File: src/RefractDataStructure.cc [hunk 12]
```diff
@@ -68,9 +68,46 @@ namespace drafter {
...
+                return mson::UndefinedTypeName;
+        }
+
+        return mson::UndefinedTypeName;
+    }
+
     template<typename T>
     static mson::BaseTypeName GetType(const T& type) {
-        return type.typeDefinition.typeSpecification.name.base;
+        mson::BaseTypeName nameType =  type.typeDefinition.typeSpecification.name.base;
```
Comment (pksunkara) [inline src/RefractDataStructure.cc]: Extra space after `=`. I don't know if our style rules will fix this or not when implemented.

File: src/RefractDataStructure.cc [hunk 13]
```diff
@@ -723,12 +760,22 @@ namespace drafter {
...
             }
 
             snowcrash::SourceMap<mson::Literal> sourceMap;
             sourceMap.sourceMap.append(property.sourceMap.name.sourceMap);
 
+            // check if base variable type is StringElement
+            if (!property.node.name.variable.typeDefinition.empty()) {
+                const std::string& type = property.node.name.variable.typeDefinition.typeSpecification.name.symbol.literal;
+                if (!type.empty()) {
+                    if (!refract::TypeQueryVisitor::as<refract::StringElement>(FindRootAncestor(type, GetNamedTypesRegistry()))) {
```
Comment (pksunkara) [inline src/RefractDataStructure.cc]: I am sorry but I might be confused. Why are we hardcoding this to `StringElement`? All primitive element types are possible. Aren't they?

```
# ID (number)
## Sample
123

# ID2 (ID)
## Sample
456
```

Comment (klokane) [inline src/RefractDataStructure.cc]: This is different case, *VariablePropertyName*
```
## VariableProperty (string)
### Sample
this can variate

## ObjectWithVariableProperty
- *var (VariableProperty)* (number)
```

and in MSON definition is written:
> In the case of specifying a Variable Property Name, the Value Definition MAY reference a Named Type that MUST be sub-typed from a string Primitive Type.

Comment (pksunkara) [inline src/RefractDataStructure.cc]: Ah, thanks for clearing it up. I was confused :)

File: src/RefractDataStructure.cc (hunk 12 above)
Comment (klokane) [inline src/RefractDataStructure.cc]: Yes, this will fix clang-format, but I will fix by hand for now

File: src/RefractDataStructure.cc (hunk 11 above)
Comment (klokane) [inline src/RefractDataStructure.cc]: good catch

File: src/refract/Element.h [hunk 14]
```diff
@@ -287,10 +278,26 @@ namespace refract
...
+        Element() : hasContent(false), renderStrategy(IElement::rDefault), value(TraitType::init())
         {
         }
 
+        virtual bool empty() const
+        {
+            return !hasContent;
+        }
+
+
```
Comment (pksunkara) [inline src/refract/Element.h]: Unnecessary extra line

File: src/RefractDataStructure.cc (hunk 13 above)
Comment (klokane) [inline src/RefractDataStructure.cc]: better to ask, maybe will add explaining comment to be clear

File: src/refract/Element.h (hunk 14 above)
Comment (klokane) [inline src/refract/Element.h]: will fix format-clang

File: src/refract/RenderJSONVisitor.cc [hunk 15]
```diff
@@ -9,265 +9,254 @@
...
+                }
             }
         }
 
         if (StringElement* str = TypeQueryVisitor::as<StringElement>(e.value.first)) {
-            assign(str->value, renderer.get());
+            MemberElement *m = new MemberElement;
+            IElement* v= renderer.result ? renderer.getOwnership() : new StringElement;
+            m->set(str->value, v);
+            result = m;
```
Comment (pksunkara) [inline src/refract/RenderJSONVisitor.cc]: Couldn't this be done something like this?

```cpp
result = new MemberElement;
...
result->set(str->value, v);
```

File: src/refract/RenderJSONVisitor.cc [hunk 16]
```diff
@@ -9,265 +9,254 @@
...
-            // Imitate an extend object
-            isExtend = true;
-            assign(renderer.get());
-            isExtend = false;
+        ObjectElement::ValueType members;
+        FetchMembers(e, members);
+        ObjectElement* o = new ObjectElement;
+        o->set(members);
+        o->renderType(IElement::rCompact);
+        result = o;
```
Comment (pksunkara) [inline src/refract/RenderJSONVisitor.cc]: Why the dancing around here? Am I missing something? Can't we do the following:

```cpp
result = new ObjectElement;
result->set(members);
result->renderType(IElement::rCompact);
```

File: src/refract/RenderJSONVisitor.cc [hunk 17]
```diff
@@ -9,265 +9,254 @@
...
+            return;
         }
 
-        assign(renderer.get());
+        ArrayElement::ValueType members;
+        FetchMembers(e, members);
+        ArrayElement* a = new ArrayElement;
+        a->set(members);
+        a->renderType(IElement::rCompact);
+        result = a;
```
Comment (pksunkara) [inline src/refract/RenderJSONVisitor.cc]: Similar comment to https://github.com/apiaryio/drafter/pull/199/files#r48477358

File: src/refract/RenderJSONVisitor.cc (hunk 15 above)
Comment (klokane) [inline src/refract/RenderJSONVisitor.cc]: No, `result` is downcasted onto `IElement` so you will be not able to call `set()` method

File: src/refract/RenderJSONVisitor.cc (hunk 16 above)
Comment (klokane) [inline src/refract/RenderJSONVisitor.cc]: same as above

File: src/refract/RenderJSONVisitor.cc (hunk 17 above)
Comment (klokane) [inline src/refract/RenderJSONVisitor.cc]: dtto

File: src/refract/Element.cc [hunk 18]
```diff
@@ -129,4 +131,276 @@ namespace refract
         }
     }
 
+    namespace {
+        struct TypeChecker {
```
Comment (pksunkara) [inline src/refract/Element.cc]: Can you add a small comment above this line briefly explaining this? Thanks.

File: src/refract/Element.cc [hunk 19]
```diff
@@ -129,4 +131,276 @@ namespace refract
...
+                        return;
+
+                    case TypeQueryVisitor::Object:
+                        doMerge<ObjectElement>(result, e);
+                        return;
+
+                    case TypeQueryVisitor::Member:
+                    case TypeQueryVisitor::Extend:
+                    case TypeQueryVisitor::Null:
+                        throw LogicError("Unappropriate kind of element to merging");
```
Comment (pksunkara) [inline src/refract/Element.cc]: `refract::LogicError`

File: src/refract/Element.cc [hunk 20]
```diff
@@ -129,4 +131,276 @@ namespace refract
...
+                    default:
+                        throw LogicError("Element has no implemented merging");
```
Comment (pksunkara) [inline src/refract/Element.cc]: `refract::LogicError`

Comment (klokane) [inline src/refract/Element.cc]: we are in `refract` namespace, it is restfull

File: src/refract/RenderJSONVisitor.cc (hunk 15 above)
Comment (pksunkara) [inline src/refract/RenderJSONVisitor.cc]: Ah. Thought I was missing something. Thanks.

File: src/RefractAPI.cc [hunk 21]
```diff
@@ -82,10 +84,145 @@ namespace drafter {
...
+        }
+
+        const std::string& name(const mson::PropertyMember& pm) {
+            return name(pm.valueDefinition);
+        }
+
+        Members collectMembers(const mson::Elements& elements) {
+            Members members;
+
+            for (mson::Elements::const_iterator ie = elements.begin() ; ie != elements.end() ; ++ie) {
```
Comment (pksunkara) [inline src/RefractAPI.cc]: Please rename `ie` to `it`.

**Comment by pksunkara** [comment]
@klokane Finished review. Just minor stuff to fix.

File: src/RefractAPI.cc (hunk 10 above)
Comment (pksunkara) [inline src/RefractAPI.cc]: Looked again more slowly. :+1:

File: src/refract/Element.cc (hunk 18 above)
Comment (klokane) [inline src/refract/Element.cc]: Will receive container of elements via ref. Later `bool` typecasting operator will check, if all elements in container are of same type. 

It is alternative way to check it in c-tor and save bool value as result, and later just return result. Or it can be implemnted just as simple function.

I mean that was more complicated while a start it write and in a few iterations I refactor it into this.

In this case it is not important which way is used because we call `bool` casting operator just once on line 164 `if (!TypeChecker(val)) { // ...`

Comment (pksunkara) [inline src/refract/Element.cc]: I understood what this is about but I think it's better if we have a comment in the code explaining this.

Comment (klokane) [inline src/refract/Element.cc]: But in this case will be probably better to transform it into simple function

Comment (pksunkara) [inline src/refract/Element.cc]: Yeah. I will leave it to you.

File: test/fixtures/mson/inheritance-primitive.apib (hunk 9 above)
Comment (klokane) [inline test/fixtures/mson/inheritance-primitive.apib]: Probably, yes. But it is not important, so it can stay as is.
In final inheritance is used sample from `Date3` so test is able to check if it is inherited in required way

**Comment by klokane** [comment]
Review addressed, fixedup on to previous commit `Fix typo` && push --force
