### PR TITLE
Fix duplicity in generated scheme with swapped order of member object wit `fixed-type`

### LINKED ISSUE #664: De-duplicate equal object entries in schema "anyOf" field for fixed-type array
Let's assume, I have the next apib:
```
# Group Example
## GET /

+ Response 200 (application/json)
   + Attributes (array, fixed-type)
       + (object)
           + msg: 'hello' (string)
           + id: 2 (number)
       + (object)
           + msg: 'bye' (string)
           + id: 3 (number)
```

And for this input I get such JSON Schema:
```
$ ./build/Release/drafter.exe -f json simple.apib | ./tools/refract-filter.py
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "anyOf": [
      {
        "type": "object",
        "properties": {
          "msg": {
            "type": "string"
          },
          "id": {
            "type": "number"
          }
        }
      }
    ]
  }
}
```

This is fine. I have equal structures as array's nested members and field "anyOf" contains only one member.

The next step: I swap the places of the second object fields:
```
# Group Example
## GET /

+ Response 200 (application/json)
   + Attributes (array, fixed-type)
       + (object)
           + msg: 'hello' (string)
           + id: 2 (number)
       + (object)
           + id: 3 (number)
           + msg: 'bye' (string)
```

AFAIK, in objects, there's no difference in fields order, these two objects should be equal.
But `emplace_unique` (or whatever doing the job) cannot handle this case:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "anyOf": [
      {
        "type": "object",
        "properties": {
          "msg": {
            "type": "string"
          },
          "id": {
            "type": "number"
          }
        }
      },
      {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          },
          "msg": {
            "type": "string"
          }
        }
      }
    ]
  }
}
```

What I expected to see: the same output as the first JSON Schema.

FYI, I have the latest version (4.0.0-pre2)

I think this has some relation to #566

### PR DESCRIPTION
**Pull request by klokane**
Closes #664

### CODE REVIEW

File: src/utils/so/Value.cc [hunk 1]
```diff
@@ -37,9 +37,26 @@ bool drafter::utils::so::operator==(const Number& lhs, const Number& rhs)
     return lhs.data == rhs.data;
 }
 
+namespace
+{
+    bool hasEqualMembers(const Object& lhs, const Object& rhs)
+    {
+        using itemType = typename Object::container_type::const_reference;
+        for (itemType item : lhs.data) {
```
Comment (kylef) [inline src/utils/so/Value.cc]: If I understand this logic correctly, if there is the following I think they'll be treated as equal.

LHS:

```
+ name: doe
```

RHS:

```
+ name: doe
+ additional: true
```

Since the logic loops over lhs members and verifies they are equal to rhs. Additional RHS members are ignored.

Perhaps a guard that the length of lhs and rhs are equal at the top of the function would solve this problem?

Comment (klokane) [reply src/utils/so/Value.cc]: There is on upper level checked count of members is equal. 

https://github.com/apiaryio/drafter/pull/714/files#diff-c71b7d4a5846e44057ccc118bacbe934R59

So situation you describe should not happen. But if you like I can make it in one step if you like

Comment (kylef) [reply src/utils/so/Value.cc]: @klokane you're right, I overlooked that part.
