### PR TITLE
Fix extend element

### LINKED ISSUE #217: JSON Schema generator fails on ExtendElement in enum
```
curl -s https://raw.githubusercontent.com/hassansin/foxycart-api-
blueprint/master/apiary.apib | drafter -l


error: (4)  ExtendElement must be composed from Elements of same type
```

I can't reproduce using latest drafter but getting different error

```
curl -s https://raw.githubusercontent.com/hassansin/foxycart-api-
blueprint/master/apiary.apib | drafter -l


error: (4)  ExtendElement serialization Not Implemented
```

At least part of the problem is that JSON Schema generator is not expanding elements if in `enum`, that's where the second error is coming from.

### PR DESCRIPTION
**Pull request by klokane**
This patch fix recent issues around "ExtendElement"
Fix #217 #245 

* Registration of NamedTypes now happens in "two steps"
- create and registrate empty refract element with correct type info
- create element with complex info (meta/attrs/content)

This solution will allow knowledge correct type info of referenced
element, so later while element is expanded we will receive correct
base element type for extend element merging

* Correctly handle deeper dependencies in registry for nested types definition
* Add ability to correctly handle complex types for nested type definition like `- type (array[Comlex, Types])`

### CODE REVIEW

File: src/NamedTypesRegistry.cc [hunk 1]
```diff
@@ -220,15 +343,61 @@ namespace drafter {
...
+
+        DependencyTypeInfo typeInfo(found);
+
+        std::sort(found.begin(), found.end(), InheritanceComparator(typeInfo));
+
+#ifdef DEBUG_DEPENDENCIES
+        std::cout << "==BASE TYPE ORDER==" << std::endl;
+#endif /* DEBUG_DEPENDENCIES */
+
+#if 1
```
Comment (klokane) [inline src/NamedTypesRegistry.cc]: remove this `#ifdef`

File: test/fixtures/extend/circular.apib [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+- (array[B])
+
+## B (enum)
+- (A)
+- (array[A])
+
+
+
+
+
```
Comment (pksunkara) [inline test/fixtures/extend/circular.apib]: Why all these extra lines?

File: test/fixtures/extend/circular.json [hunk 3]
```diff
@@ -0,0 +1,182 @@
...
+                              "element": "asset",
+                              "meta": {
+                                "classes": [
+                                  "messageBody"
+                                ]
+                              },
+                              "attributes": {
+                                "contentType": "application/json"
+                              },
+                              "content": "[\n  \"\",\n  \"\"\n]"
```
Comment (pksunkara) [inline test/fixtures/extend/circular.json]: I wonder if the JSON generated here is the correct one. /cc @w-vi What do you think?

**Comment by Baggz** [comment]
<3

File: test/fixtures/extend/circular.apib (hunk 2 above)
Comment (klokane) [inline test/fixtures/extend/circular.apib]: Probably cut/past & edit cycle. Will cut

File: test/fixtures/extend/circular.json (hunk 3 above)
Comment (klokane) [inline test/fixtures/extend/circular.json]: Hard to say, but it is real extreme. In real life it has no solution because you are not able to determine real value. So there is fallback to empty string in enum.

Comment (w-vi) [inline test/fixtures/extend/circular.json]: The whole thing does not make any sense so having such JSON is OK, what else could be there?

File: test/fixtures/extend/many.json [hunk 4]
```diff
@@ -0,0 +1,415 @@
...
+                              "element": "asset",
+                              "meta": {
+                                "classes": [
+                                  "messageBodySchema"
+                                ]
+                              },
+                              "attributes": {
+                                "contentType": "application/schema+json"
+                              },
+                              "content": "{\n  \"$schema\": \"http://json-schema.org/draft-04/schema#\",\n  \"type\": \"object\",\n  \"properties\": {\n    \"loc\": {}\n  }\n}"
```
Comment (w-vi) [inline test/fixtures/extend/many.json]: Schema is incorrect it should be an array, it probably is a bug and should be a separate fix

**Comment by w-vi** [comment]
@klokane @pksunkara Apart from the test comments I think it's good to go

**Comment by klokane** [comment]
Ok, so I will cut `extend/circular.apib` and we can go

**Comment by klokane** [comment]
Updated

**Comment by w-vi** [comment]
@pksunkara If you have nothing more to add please merge as I'm cool with the current state

File: test/fixtures/extend/many.json (hunk 4 above)
Comment (pksunkara) [inline test/fixtures/extend/many.json]: @w-vi Can you please create an issue so we don't forget this? Thanks.

File: test/test-ElementFactoryTest.cc [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+#include "refract/Visitors.h"
+#include "refract/Element.h"
+
+#include "RefractElementFactory.h"
+
+
+using namespace refract;
+using namespace drafter;
+
+TEST_CASE("Create empty primitive element","[ElementFactory]") {
```
Comment (pksunkara) [inline test/test-ElementFactoryTest.cc]: Shouldn't the `{` be in new lines for the tests?

Comment (klokane) [inline test/test-ElementFactoryTest.cc]: There are in `test-ApplyVisitorTest.cc` in same position.
But we should finally create clang-format config and add into repo

File: src/NamedTypesRegistry.cc [hunk 6]
```diff
@@ -220,15 +343,59 @@ namespace drafter {
...
         for (DataStructures::const_iterator i = found.begin(); i != found.end(); ++i) {
 
             if (!i->node->name.symbol.literal.empty()) {
+
+                const std::string& name = i->node->name.symbol.literal;
                 refract::IElement* element = MSONToRefract(*i);
+#ifdef DEBUG_DEPENDENCIES
+                refract::TypeQueryVisitor v;
+                v.visit(*element);
+                std::cout
```
Comment (pksunkara) [inline src/NamedTypesRegistry.cc]: Can you please move all of this `cout` to a single line?

File: src/NamedTypesRegistry.cc [hunk 7]
```diff
@@ -220,15 +343,59 @@ namespace drafter {
...
+            GetNamedTypesRegistry().add(element);
+        }
 
         for (DataStructures::const_iterator i = found.begin(); i != found.end(); ++i) {
 
             if (!i->node->name.symbol.literal.empty()) {
+
+                const std::string& name = i->node->name.symbol.literal;
                 refract::IElement* element = MSONToRefract(*i);
+#ifdef DEBUG_DEPENDENCIES
```
Comment (pksunkara) [inline src/NamedTypesRegistry.cc]: Please make sure there is an empty line before and after these kind of blocks for easier reading comprehension.

File: src/NamedTypesRegistry.cc [hunk 8]
```diff
@@ -137,25 +160,83 @@ namespace drafter {
...
 
-                // map inheritance
+                // map inheritance && element
                 for (DataStructures::const_iterator i = elements.begin() ; i != elements.end() ; ++i) {
+
+                    nameToElement[name(i->node)] = &(*i->node);
+
                     if (hasParent(i->node)) {
                         childToParent[name(i->node)] = parent(i->node);
+#ifdef DEBUG_DEPENDENCIES
```
Comment (pksunkara) [inline src/NamedTypesRegistry.cc]: As said in other comment, please go through all occurrences of these blocks and make sure they have an empty line before and after them.

**Comment by pksunkara** [comment]
Reviewed.

**Comment by klokane** [comment]
@pksunkara can you please do ALL STYLE RELATED comments in one "turn"
It is really tedious make again and again rebase and push force just with style changes

**Comment by pksunkara** [comment]
@klokane Sorry, But I do the style comments when I go through the code. :(

**Comment by w-vi** [comment]
Again style discussion, please @pksunkara have a look at https://github.com/apiaryio/snowcrash/issues/360 and give it a try so we can start using it
