### PR TITLE
Prevent recursion while converting MSON type members to refract

### LINKED ISSUE #267: Regression: Recursion when converting MSON Member to Refract with default types
With the following API Blueprint, we are looping over during converting the MSON Member to Refract.

```apib
## Data Structures
### Object
+ thing (optional, array[])
    + foo: bar
```

### PR DESCRIPTION
**Pull request by kylef**
While the type is the same as the default nested type, we would be causing recursion by calling ourself with the same arguments.

Fixes #267.

---

Perhaps there is a better solution, welcome to suggestions.

### CODE REVIEW

File: src/RefractDataStructure.cc [hunk 1]
```diff
@@ -900,13 +900,13 @@ namespace drafter {
...
+                else if (nameType != defaultNestedType) {
+                    return MsonMemberToRefract<Trait>(input, defaultNestedType, defaultNestedType);
+                }
             }
-
-            default:
-                throw snowcrash::Error("unknown type of mson member", snowcrash::MSONError);
         }
+
+        throw snowcrash::Error("unknown type of mson member", snowcrash::MSONError);
```
Comment (kylef) [inline src/RefractDataStructure.cc]: I didn't find any other tests for `unknown type of moon member`, unsure how we can go about testing this. Would love suggestions.

**Comment by kylef** [comment]
Let's get #264 merged first and I will rebase this once that's done.

**Comment by w-vi** [comment]
Testing exceptions and errors is not easy and we are not testing many of them yet. This needs to be addressed as well as other issues in our testing infrastructure.
