### PR TITLE
Fix regression issues

### LINKED ISSUE #117: Unable to render when named types are nested in array
Given the below blueprint, 

```apib
# GET /
+ Response 200 (application/json)
    + Attributes (array[User])
​
# Data Structures
## User
+ username: pksunkara
```

The `payload.body` is not getting rendering because there is a problem with expanding MSON.

### LINKED ISSUE #136: Regression: Value for enum is not getting rendered
# Example

```apib
FORMAT: 1A

# Example

# Data Structures
## A
+ a: TAC (B, required)

## B (enum)
- TAC

# GET /
+ Response 200 (application/json)
    + Attributes (A)
```

# Old behaviour

Response body is getting rendered as:

```json
{"a": "TAC"}
```

# New behaviour

```json
{"a": {}}
```

# Expected

Old behaviour is correct.

### LINKED ISSUE #137: Regression: Mixins are not getting rendered
# Example

```apib
FORMAT: 1A

# Example

# Data Structures
## A (object)
+ Include B

## B (object)
+ b: b

# GET /
+ Response 200 (application/json)
    + Attributes (A)
```

# Old behaviour
Response body is rendered as

```json
{"b": "b"}
```

# New behaviour
Response body is an empty JSON object.

# Expected
Old behaviour is correct.

### LINKED ISSUE #141: Regression: Member reference is not getting rendered
# Example

```apib
FORMAT: 1A

# Example

# Data Structures

## B (object)
+ b: b

## A (object)
+ a (B)

# GET /
+ Response 200 (application/json)
    + Attributes (A)
```

# Old behaviour
Response body is getting rendered as

```json
{"a": {"b": "b"}}
```

# New behaviour
Response body is getting rendered as

```json
{"a": {}}
```

# Expected
Old behaviour is correct.

### PR DESCRIPTION
**Pull request by klokane**
- Fixes #117
- Fixes #141 
- Fixes #137 
- Fixes #136 

Ready for code review

### CODE REVIEW

**Comment by klokane** [comment]
Code is still not ready to merge, needed a little bit polish, but firstly I want finish #136

File: src/RefractDataStructure.cc [hunk 1]
```diff
@@ -453,6 +511,7 @@ namespace drafter {
             }
         };
 
+        /*
```
Comment (pksunkara) [inline src/RefractDataStructure.cc]: Why not removing the whole thing?

Comment (klokane) [inline src/RefractDataStructure.cc]: This one of parts need to be polished, another one is RefractDataStructure.cc#L1024
Additionaly all `Extract*` functors should inherited from one ancestor.

Comment (klokane) [inline src/RefractDataStructure.cc]: will fix after finish #136

**Comment by klokane** [comment]
Status updated, see comment for PullRequest

**Comment by klokane** [comment]
Ready fore review

File: src/refract/RenderJSONVisitor.cc [hunk 2]
```diff
@@ -11,6 +11,8 @@
 #include "sosJSON.h"
 #include <sstream>
 
+#include <iostream>
```
Comment (pksunkara) [inline src/refract/RenderJSONVisitor.cc]: Unnecessary header.

File: test/test-RefractAPITest.cc [hunk 3]
```diff
@@ -21,3 +21,9 @@ TEST_REFRACT("api", "request-only");
 TEST_REFRACT("api", "asset");
 TEST_REFRACT("api", "attributes-references");
 TEST_REFRACT("api", "action-request-attributes");
+
+// regressions
+TEST_REFRACT("api", "attributes-array-nested-named-type");
+TEST_REFRACT("api", "attributes-named-type-member-reference");
+TEST_REFRACT("api", "attributes-named-type-mixin");
+TEST_REFRACT("api", "attributes-named-type-enum");
```
Comment (pksunkara) [inline test/test-RefractAPITest.cc]: Please call this `attributes-named-type-enum-reference`, since named type is not an enum but is in fact referencing an `enum`.

File: src/refract/RenderJSONVisitor.cc [hunk 4]
```diff
@@ -223,6 +225,61 @@ namespace refract
...
+
+                if ((*it)->element() == "enum") {
+                    return true;
+                }
+            }
+            return false;
+        }
+    }
+
+
```
Comment (pksunkara) [inline src/refract/RenderJSONVisitor.cc]: Extra empty line.

File: src/refract/RenderJSONVisitor.cc [hunk 5]
```diff
@@ -223,6 +225,61 @@ namespace refract
         assign(renderer.get());
     }
 
+    namespace {
```
Comment (pksunkara) [inline src/refract/RenderJSONVisitor.cc]: Please move this namespace to be just below the `namespace refract` declaration. Also please include the other `getSample`, `getDefault`, `isTypeAttribute` functions in this namespace.

**Comment by pksunkara** [comment]
@klokane Just minor style issues. If you can fix them soon. I will merge this.

File: src/refract/RenderJSONVisitor.cc (hunk 5 above)
Comment (klokane) [inline src/refract/RenderJSONVisitor.cc]: Why? There is no reason to expose them. It is intended for anonymous namespace

Comment (pksunkara) [inline src/refract/RenderJSONVisitor.cc]: I am asking you to move the anonymous namespace to be just below the refract namespace declaration. Not remove it completely.

```
namespace refract
{
    namespace {
```

Comment (pksunkara) [inline src/refract/RenderJSONVisitor.cc]: Also include the above listed functions in the anonymous namespace.

Comment (klokane) [inline src/refract/RenderJSONVisitor.cc]: This functions are used just in `void RenderJSONVisitor::visit(const ArrayElement& e)`
So I mean it is logical to have then just before this method where are used

Comment (pksunkara) [inline src/refract/RenderJSONVisitor.cc]: Okay.

**Comment by klokane** [comment]
All other adressed (hope :)
